apiVersion: v1
kind: ServiceAccount
metadata:
  name: lrm-operator
  namespace: lrm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lrm-operator
rules:
  # LockableResourceTemplate
  - apiGroups: [lrm.openlab.io]
    resources: [lockableresourcetemplates]
    verbs: [get, list, watch]
  - apiGroups: [lrm.openlab.io]
    resources: [lockableresourcetemplates/status]
    verbs: [get, patch, update]
  # LockableResource
  - apiGroups: [lrm.openlab.io]
    resources: [lockableresources]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [lrm.openlab.io]
    resources: [lockableresources/status]
    verbs: [get, patch, update]
  # Pods
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
  # Events
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  # Leader election
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lrm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lrm-operator
subjects:
  - kind: ServiceAccount
    name: lrm-operator
    namespace: lrm-system
